---
- hosts: localhost
  gather_facts: False
  roles:
  - cluster-inventory

- hosts: cluster
  vars:
    ib_ip: "{{ hostvars[inventory_hostname]['networks'][lln_name] }}"
  gather_facts: False
  roles:
  - attach-ib
  - glusterfs
  - copy-authorized-keys
...
