---
- hosts: localhost
  vars:
    cluster_name: swarm-bharat
    cluster_user: fedora
  gather_facts: no
  roles:
  - add-networks

- hosts: workers
  gather_facts: no
  roles:
  - attach-ib
  - { role: glusterfs, gluster_src: '10.3.0.12:/swarm_vol' }
...
