---
- name: get node and master addresses
  shell: "openstack coe cluster show {{ cluster_name }} -c master_addresses -c node_addresses -f json"
  register: result_addresses

- name: get list of servers
  shell: "openstack server list -c ID -c Networks -f json"
  register: result_servers

- name: convert results to json
  set_fact:
    addresses: "{{ result_addresses.stdout | from_json }}"
    servers: "{{ result_servers.stdout | from_json }}"
