---
- name: Additional public keys to be authorized to access the cluster nodes
  authorized_key:
    key: "{{ lookup('file', 'public_keys/' + item) }}"
    user: "{{ ansible_user }}"
    state: present
  loop:
  - stig
  - doug
  ignore_errors: True
...
