---
- name: delete bdn default route
  shell: route del default eth4
  ignore_errors: True
  become: True

- name: restart NetworkManager service
  shell: systemctl restart NetworkManager
  become: True

- name: Ensure any required kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  become: True
  with_items: "{{ ib_mods }}"

- name: Make sure required modules are loaded at boot via /etc/modules-load.d
  file:
    path: /etc/modules-load.d/ib-mods.conf
    state: absent
  become: True

- name: Copy ifcfg-ib0 port up
  template:
    src: ifcfg-ib0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-ib0
  become: True

- name: Stop ib0 interface
  shell: ifup ib0
  become: True

- name: Start ib0 interface
  shell: ifup ib0
  become: True
...
