---
# Task flow inspired by MichaelRigart.interfaces role - thanks markgoddard
# # Some systems do not support /etc/modules-load.d, in which case we fall back
# # to /etc/modules.
- name: Check whether /etc/modules-load.d exists
  stat:
    path: /etc/modules-load.d
  register: modules_load_stat

- name: Ensure any required kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  become: True
  with_items: "{{ ib_mods }}"

- name: Make sure required modules are loaded at boot via /etc/modules-load.d
  lineinfile:
    dest: /etc/modules-load.d/ib-mods.conf
    line: "{{ item }}"
    create: yes
  become: True
  when: modules_load_stat.stat.exists
  with_items: "{{ ib_mods }}"

- name: Make sure required modules are loaded at boot via /etc/modules
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  become: True
  when: not modules_load_stat.stat.exists
  with_items: "{{ ib_mods }}"

- name: Copy ifcfg-ib0 port up
  template:
    src: ifcfg-ib0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-ib0
  become: True
  notify: Reload ib0 interface 
...
